//! File deployment, idempotency checks, and legacy EA archiving.

use crate::config::BrokerConfig;
use super::compiler::DeployCompileStatus;
use super::discovery::DiscoveredTerminal;
use super::error::DeployError;
use super::sources::SourceFiles;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DeployFileStatus {
    Created,
    Updated,
    SkippedIdentical,
    Archived,
    Failed(DeployError),
}

#[derive(Debug, Clone)]
pub struct FileDeployResult {
    pub rel_name: String,
    pub target_path: PathBuf,
    pub status: DeployFileStatus,
}

#[derive(Debug, Clone)]
pub struct TerminalDeployReport {
    pub terminal_name: String,
    pub terminal_dir: PathBuf,
    pub mql5_dir: PathBuf,
    pub results: Vec<FileDeployResult>,
    pub compile_status: Option<DeployCompileStatus>,
    #[allow(dead_code)]
    pub broker_compile_results: Vec<(String, DeployCompileStatus)>,
}

#[derive(Debug, Clone, Default)]
pub struct DeployReport {
    pub enabled: bool,
    pub terminals: Vec<TerminalDeployReport>,
    pub warnings: Vec<String>,
}

pub fn broker_ea_name(broker: &BrokerConfig) -> String {
    let name: String = broker.name.chars().map(|c| {
        if c.is_ascii_alphanumeric() || c == '-' { c } else { '_' }
    }).take(64).collect();
    format!("TickCollector_{}_{}.mq5", broker.id, name)
}

pub fn deploy_broker_eas(
    terminal: &DiscoveredTerminal,
    sources: &SourceFiles,
    brokers: &[BrokerConfig],
) -> Vec<FileDeployResult> {
    brokers.iter().map(|broker| {
        let host = match broker.host.as_str() {
            "0.0.0.0" => "127.0.0.1",
            "::" => "::1",
            host => host,
        };
        let host = host.replace('\\', "\\\\").replace('"', "\\\"").replace('\r', "\\r").replace('\n', "\\n");
        let content = format!(
            "// Generated by TickScope. Connection settings come from the app config.\n#define TICKSCOPE_BROKER_ID {}\n#define TICKSCOPE_SERVER_HOST \"{}\"\n#define TICKSCOPE_SERVER_PORT {}\n{}",
            broker.id, host, broker.port, sources.tick_collector
        );
        deploy_file_idempotent(&terminal.mql5_dir.join("Experts/TickScope").join(broker_ea_name(broker)), &content)
    }).collect()
}

pub fn tsv_safe(value: &str) -> String {
    value
        .chars()
        .map(|character| match character {
            '\t' | '\r' | '\n' => ' ',
            character => character,
        })
        .collect()
}

pub fn connection_map_contents(brokers: &[BrokerConfig]) -> String {
    let mut contents = String::from("TICKSCOPE\t1\n");
    for broker in brokers {
        let server_hint = tsv_safe(&broker.name);
        let symbol = tsv_safe(&broker.symbol);
        contents.push_str(&format!(
            "{}\t{}\t{}\t{}\n",
            broker.id, server_hint, symbol, broker.port
        ));
    }
    contents.push_str("END\n");
    contents
}

pub fn deploy_file_idempotent(target_path: &Path, content: &str) -> FileDeployResult {
    let rel_name = target_path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "file".to_string());

    if target_path.exists() {
        match fs::read(target_path) {
            Ok(existing_bytes) => {
                if existing_bytes == content.as_bytes() {
                    return FileDeployResult {
                        rel_name,
                        target_path: target_path.to_path_buf(),
                        status: DeployFileStatus::SkippedIdentical,
                    };
                }
                // Different content: update
                if let Err(e) = fs::write(target_path, content.as_bytes()) {
                    return FileDeployResult {
                        rel_name,
                        target_path: target_path.to_path_buf(),
                        status: DeployFileStatus::Failed(DeployError::FileWrite {
                            path: target_path.to_path_buf(),
                            message: e.to_string(),
                        }),
                    };
                }
                return FileDeployResult {
                    rel_name,
                    target_path: target_path.to_path_buf(),
                    status: DeployFileStatus::Updated,
                };
            }
            Err(e) => {
                return FileDeployResult {
                    rel_name,
                    target_path: target_path.to_path_buf(),
                    status: DeployFileStatus::Failed(DeployError::FileRead {
                        path: target_path.to_path_buf(),
                        message: e.to_string(),
                    }),
                };
            }
        }
    }

    // Target does not exist: create
    if let Some(parent) = target_path.parent() {
        if !parent.exists() {
            if let Err(e) = fs::create_dir_all(parent) {
                return FileDeployResult {
                    rel_name,
                    target_path: target_path.to_path_buf(),
                    status: DeployFileStatus::Failed(DeployError::CreateDir {
                        path: parent.to_path_buf(),
                        message: e.to_string(),
                    }),
                };
            }
        }
    }

    match fs::write(target_path, content.as_bytes()) {
        Ok(_) => FileDeployResult {
            rel_name,
            target_path: target_path.to_path_buf(),
            status: DeployFileStatus::Created,
        },
        Err(e) => FileDeployResult {
            rel_name,
            target_path: target_path.to_path_buf(),
            status: DeployFileStatus::Failed(DeployError::FileWrite {
                path: target_path.to_path_buf(),
                message: e.to_string(),
            }),
        },
    }
}

pub fn archive_legacy_generated_broker_eas(terminal: &DiscoveredTerminal) -> Vec<FileDeployResult> {
    const GENERATED_MARKER: &str = "// Generated by TickScope. Connection settings come from the app config.";

    let legacy_dir = terminal.mql5_dir.join("Experts").join("TickScope");
    let canonical_mql5 = match terminal.mql5_dir.canonicalize() {
        Ok(path) => path,
        Err(_) => return Vec::new(),
    };
    let canonical_legacy_dir = match legacy_dir.canonicalize() {
        Ok(path) if path.starts_with(&canonical_mql5) => path,
        _ => return Vec::new(),
    };
    let entries = match fs::read_dir(&canonical_legacy_dir) {
        Ok(entries) => entries,
        Err(_) => return Vec::new(),
    };
    let mut legacy_sources = Vec::new();
    for entry in entries.flatten() {
        let source_path = entry.path();
        let is_legacy_name = source_path
            .file_name()
            .and_then(|name| name.to_str())
            .map(|name| name.starts_with("TickCollector_") && name.ends_with(".mq5"))
            .unwrap_or(false);
        if !is_legacy_name || !source_path.is_file() {
            continue;
        }
        if fs::read_to_string(&source_path)
            .map(|contents| contents.contains(GENERATED_MARKER))
            .unwrap_or(false)
        {
            legacy_sources.push(source_path);
        }
    }
    if legacy_sources.is_empty() {
        return Vec::new();
    }

    let archive_dir = terminal
        .mql5_dir
        .join("Files")
        .join("TickScope")
        .join("legacy_broker_eas");
    if let Err(error) = fs::create_dir_all(&archive_dir) {
        return vec![FileDeployResult {
            rel_name: "legacy_broker_eas".to_string(),
            target_path: archive_dir.clone(),
            status: DeployFileStatus::Failed(DeployError::CreateDir {
                path: archive_dir,
                message: error.to_string(),
            }),
        }];
    }
    let canonical_archive_dir = match archive_dir.canonicalize() {
        Ok(path) if path.starts_with(&canonical_mql5) => path,
        _ => {
            return vec![FileDeployResult {
                rel_name: "legacy_broker_eas".to_string(),
                target_path: archive_dir,
                status: DeployFileStatus::Failed(DeployError::Archive(
                    "Archive directory resolves outside the MT5 data directory".to_string(),
                )),
            }];
        }
    };
    let mut results = Vec::new();
    for source_path in legacy_sources {
        for source in [source_path.clone(), source_path.with_extension("ex5")] {
            let Some(file_name) = source.file_name() else {
                continue;
            };
            let path = canonical_archive_dir.join(file_name);
            if !source.is_file() {
                continue;
            }
            let rel_name = path
                .file_name()
                .map(|name| name.to_string_lossy().to_string())
                .unwrap_or_else(|| "legacy EA".to_string());
            let status = if path.exists() {
                DeployFileStatus::Failed(DeployError::Archive("Archive destination already exists; original file was kept".to_string()))
            } else {
                match fs::rename(&source, &path) {
                    Ok(()) => DeployFileStatus::Archived,
                    Err(error) => DeployFileStatus::Failed(DeployError::Archive(error.to_string())),
                }
            };
            results.push(FileDeployResult {
                rel_name,
                target_path: path,
                status,
            });
        }
    }
    results
}

pub fn deploy_to_terminal(terminal: &DiscoveredTerminal, sources: &SourceFiles) -> TerminalDeployReport {
    let mut results = Vec::new();

    let ea_path = terminal.mql5_dir.join("Experts").join("TickCollector.mq5");
    results.push(deploy_file_idempotent(&ea_path, &sources.tick_collector));

    let proto_path = terminal
        .mql5_dir
        .join("Include")
        .join("TickScope")
        .join("Protocol.mqh");
    results.push(deploy_file_idempotent(&proto_path, &sources.protocol_mqh));

    let socket_path = terminal
        .mql5_dir
        .join("Include")
        .join("TickScope")
        .join("SocketClient.mqh");
    results.push(deploy_file_idempotent(&socket_path, &sources.socket_client_mqh));

    TerminalDeployReport {
        terminal_name: terminal.friendly_name.clone(),
        terminal_dir: terminal.terminal_dir.clone(),
        mql5_dir: terminal.mql5_dir.clone(),
        results,
        compile_status: None,
        broker_compile_results: Vec::new(),
    }
}
